import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./component/Navigation";
import localFont from 'next/font/local';
import Footer from "./component/Footer";


const ciguatera = localFont({
  src: "./fonts/ciguatera.ttf",
  variable: "--font-ciguatera",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${ciguatera.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Navigation  />

        {children}

        <Footer/>
      </body>
    </html>
  );
}
